from __future__ import annotations

from typing import Protocol, Sequence

from dlt_utils.adapters.kafka.types import KafkaMessage


class KafkaWaiter(Protocol):
    def prepare(self, topic: str, *, start_from: str = "end") -> None: ...
    def wait_for_key(self, topic: str, key: str, *, timeout_s: int, poll_interval_s: float) -> KafkaMessage: ...
    def wait_for_any(self, topic: str, keys: Sequence[str], *, timeout_s: int, poll_interval_s: float) -> KafkaMessage: ...
    def close(self) -> None: ...
